using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading;

namespace sprh
{
    public class SprhToCppCompiler
    {

        public class Options
        {
            public bool Strict { get; set; } = false;
            public bool Debug { get; set; } = false;
            public int SleepTimeMs { get; set; } = 0;
            public int BufferSize { get; set; } = 512;
            public string InputFile { get; set; } = "input.spri";
            public string OutputFile { get; set; } = "output.spro";
        }

        private string? _sourceFileName;
        private Options? _options;

        public void Compile(string sprhFilePath, string cppFilePath, Options? options = null)
        {
            _options = options ?? new Options();
            _sourceFileName = Path.GetFileName(sprhFilePath);

            Log($"源文件: {sprhFilePath}");
            Log($"目标文件: {cppFilePath}");

            Log("正在读取源文件...");
            string rawCode = File.ReadAllText(sprhFilePath);

            Log("正在移除注释...");
            string noComments = SprhCommentRemover.RemoveComments(rawCode, true);
            Log("注释移除完成。");

            Log("正在解析指令...");
            var instructions = ParseInstructions(noComments);
            Log($"解析到 {instructions.Count} 条指令。");

            Log("正在计算跳转配对（简单匹配，忽略嵌套）...");
            var jumpPairs = PrecomputeJumpPairs(instructions);
            Log("跳转配对完成。");

            Log("正在生成 C++ 源代码...");
            string cppSource = GenerateCppSource(instructions, jumpPairs);
            Log("源代码生成完成。");

            Log("正在写入文件...");
            Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
            File.WriteAllText(cppFilePath, cppSource, Encoding.GetEncoding("GBK"));
            Log("写入完成。");
        }

        private void Log(string message)
        {
            if (!_options.Debug) return;
            var originalColor = Console.ForegroundColor;
            try
            {
                Console.ForegroundColor = ConsoleColor.Cyan;
                Console.WriteLine($"[Log] {message}");
            }
            finally
            {
                Console.ForegroundColor = originalColor;
            }
            if (_options.SleepTimeMs > 0) Thread.Sleep(_options.SleepTimeMs);
        }

        private List<(char Cmd, char Param)> ParseInstructions(string code)
        {
            var list = new List<(char, char)>();
            for (int i = 0; i < code.Length; i += 2)
                list.Add((code[i], code[i + 1]));
            return list;
        }


        private Dictionary<int, int> PrecomputeJumpPairs(List<(char Cmd, char Param)> instructions)
        {
            var pairs = new Dictionary<int, int>();
            for (int i = 0; i < instructions.Count; i++)
            {
                var (cmd, param) = instructions[i];
                char closeChar = '\0';
                if (cmd == '[') closeChar = ']';
                else if (cmd == '{') closeChar = '}';
                else if (cmd == '(') closeChar = ')';
                else continue;


                for (int j = i + 1; j < instructions.Count; j++)
                {
                    var (jCmd, jParam) = instructions[j];
                    if (jCmd == '/' && jParam == closeChar)
                    {
                        pairs[i] = j;
                        break;
                    }
                }
                if (!pairs.ContainsKey(i))
                    throw new InvalidDataException($"未找到匹配的 /{closeChar} 对应指令 {i}");
            }
            return pairs;
        }

        private string GenerateCppSource(List<(char Cmd, char Param)> instructions, Dictionary<int, int> jumpPairs)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// Generated by SPRH to C++ Compiler");
            sb.AppendLine();
            sb.AppendLine("#include <iostream>");
            sb.AppendLine("#include <fstream>");
            sb.AppendLine("#include <stack>");
            sb.AppendLine("#include <cstdlib>");
            sb.AppendLine("#include <cstring>");
            sb.AppendLine("#include <cstdio>");
            sb.AppendLine("#include <clocale>");
            sb.AppendLine("#include <ctime>");
            sb.AppendLine("#ifdef _WIN32");
            sb.AppendLine("#include <conio.h>");
            sb.AppendLine("#define GETCH() _getche()");
            sb.AppendLine("#else");
            sb.AppendLine("#include <termios.h>");
            sb.AppendLine("#include <unistd.h>");
            sb.AppendLine("int getch() {");
            sb.AppendLine("    struct termios oldt, newt;");
            sb.AppendLine("    char ch;");
            sb.AppendLine("    tcgetattr(STDIN_FILENO, &oldt);");
            sb.AppendLine("    newt = oldt;");
            sb.AppendLine("    newt.c_lflag &= ~ICANON;");
            sb.AppendLine("    tcsetattr(STDIN_FILENO, TCSANOW, &newt);");
            sb.AppendLine("    read(STDIN_FILENO, &ch, 1);");
            sb.AppendLine("    tcsetattr(STDIN_FILENO, TCSANOW, &oldt);");
            sb.AppendLine("    return ch;");
            sb.AppendLine("}");
            sb.AppendLine("#define GETCH() getch()");
            sb.AppendLine("#endif");
            sb.AppendLine();

            sb.AppendLine($"#define BUFSIZE {_options.BufferSize}");
            sb.AppendLine();

            sb.AppendLine($"const char* source_filename = \"{_sourceFileName}\";");
            string escapedInput = _options.InputFile.Replace("\\", "\\\\");
            string escapedOutput = _options.OutputFile.Replace("\\", "\\\\");
            sb.AppendLine($"const char* input_filename = \"{escapedInput}\";");
            sb.AppendLine($"const char* output_filename  = \"{escapedOutput}\";");

            sb.AppendLine("void runtime_error(const char* reason, int ip, char cmd, char param) {");
            sb.AppendLine("    std::cerr << \"[Warn] 程序发生异常!\" << std::endl;");
            sb.AppendLine("    std::cerr << \"[Error] 在执行指令 \\\"\" << cmd << param << \"\\\" (ip=\" << ip << \") 时出错，原因:\" << reason << std::endl;");
            sb.AppendLine("    std::cerr << \"[Warn] 停止执行 \" << source_filename << std::endl;");
            sb.AppendLine("    exit(1);");
            sb.AppendLine("}");
            sb.AppendLine();

            sb.AppendLine("int hex_char_to_int(char c) {");
            sb.AppendLine("    if (c >= '0' && c <= '9') return c - '0';");
            sb.AppendLine("    if (c >= 'A' && c <= 'F') return c - 'A' + 10;");
            sb.AppendLine("    if (c >= 'a' && c <= 'f') return c - 'a' + 10;");
            sb.AppendLine("    return -1;");
            sb.AppendLine("}");
            sb.AppendLine();

            sb.AppendLine("unsigned char buf[BUFSIZE][BUFSIZE] = {{0}};");
            sb.AppendLine("int x = 0, y = 0;");
            sb.AppendLine("unsigned char variable = 0;");
            sb.AppendLine("std::stack<unsigned char> stk; // 栈");
            sb.AppendLine("std::ifstream fin; // 输入文件流（惰性打开）");
            sb.AppendLine();

            string[] labels = new string[instructions.Count];
            for (int i = 0; i < instructions.Count; i++)
                labels[i] = $"L{i}";

            sb.AppendLine("int main() {int ch;");

            sb.AppendLine("    srand((unsigned)time(0)); // 初始化随机数种子");
            sb.AppendLine("#ifdef _WIN32");
            sb.AppendLine("    system(\"chcp 65001 > nul\");");
            sb.AppendLine("#endif");
            sb.AppendLine("    setlocale(LC_ALL, \"\");");
            sb.AppendLine();

            for (int idx = 0; idx < instructions.Count; idx++)
            {
                var (cmd, param) = instructions[idx];
                sb.AppendLine();
                sb.AppendLine($"{labels[idx]}: ;");

                if (_options.Debug)
                {
                    sb.AppendLine($"    std::cerr << \"[Log] 执行代码:{cmd}{param} at ip=\" << {idx} << std::endl;");
                    sb.AppendLine($"    std::cerr << \"[Log] 当前状态: x=\" << x << \",y=\" << y << \",num=\" << (int)buf[x][y] << std::endl;");
                }

                if (cmd == '/' && (param == ']' || param == '}' || param == ')'))
                {
                    if (_options.Debug)
                        sb.AppendLine($"    std::cerr << \"[Log] 空操作 (/{param})\" << std::endl;");
                    if (idx + 1 < instructions.Count)
                        sb.AppendLine($"    goto {labels[idx + 1]};");
                    else
                        sb.AppendLine($"    goto end;");
                    continue;
                }

                bool isJump = GenerateInstructionCode(sb, cmd, param, idx, labels, jumpPairs);

                if (!isJump && idx + 1 < instructions.Count)
                {
                    sb.AppendLine($"    goto {labels[idx + 1]};");
                }
            }

            sb.AppendLine("end:");
            sb.AppendLine("    if (fin.is_open()) fin.close();");
            sb.AppendLine("    return 0;");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private bool GenerateInstructionCode(StringBuilder sb, char cmd, char param, int idx, string[] labels, Dictionary<int, int> jumpPairs)
        {

            if (cmd == '[' || cmd == '{' || cmd == '(')
            {
                char dir = char.ToLower(param);
                if (dir != 'u' && dir != 'd' && dir != 'l' && dir != 'r')
                {
                    sb.AppendLine($"    runtime_error(\"未知的方向参数\", {idx}, '{cmd}', '{param}');");
                    return true;
                }

                sb.AppendLine($"    int targetX = x, targetY = y;");
                sb.AppendLine($"    switch('{dir}') {{");
                sb.AppendLine($"        case 'u': targetY = y - 1; break;");
                sb.AppendLine($"        case 'd': targetY = y + 1; break;");
                sb.AppendLine($"        case 'l': targetX = x - 1; break;");
                sb.AppendLine($"        case 'r': targetX = x + 1; break;");
                sb.AppendLine($"    }}");
                sb.AppendLine($"    if (targetX < 0 || targetX >= BUFSIZE || targetY < 0 || targetY >= BUFSIZE)");
                sb.AppendLine($"        runtime_error(\"缓冲区溢出\", {idx}, '{cmd}', '{param}');");

                string condition;
                if (cmd == '[')
                    condition = $"buf[x][y] == buf[targetX][targetY]";
                else if (cmd == '{')
                    condition = $"buf[x][y] > buf[targetX][targetY]";
                else // '('
                    condition = $"buf[x][y] < buf[targetX][targetY]";

                if (_options.Debug)
                {
                    sb.AppendLine($"    std::cerr << \"[Log] 当前位置数值:\" << (int)buf[x][y] << \",目标数值:\" << (int)buf[targetX][targetY] << std::endl;");
                }

                if (!jumpPairs.TryGetValue(idx, out int targetIdx))
                {
                    sb.AppendLine($"    runtime_error(\"未找到匹配的闭括号\", {idx}, '{cmd}', '{param}');");
                    return true;
                }

                sb.AppendLine($"    if ({condition}) goto {labels[targetIdx]};");
                return true;
            }

            // 移动指令 U/D/L/R 现在可以接受十六进制、v、?
            char lowerCmd = char.ToLower(cmd);
            if (lowerCmd == 'u' || lowerCmd == 'd' || lowerCmd == 'l' || lowerCmd == 'r')
            {
                return GenerateMoveInstruction(sb, cmd, param, idx);
            }

            if (IsHexInstruction(cmd))
            {
                sb.AppendLine($"    {{");
                sb.AppendLine($"        int val = hex_char_to_int('{param}');");
                sb.AppendLine($"        if (val == -1) runtime_error(\"参数不是十六进制数\", {idx}, '{cmd}', '{param}');");
                if (_options.Debug) sb.AppendLine($"        std::cerr << \"[Log] 参数:\" << '{param}' << std::endl;");

                switch (lowerCmd)
                {
                    case '*':
                        if (_options.Strict) sb.AppendLine($"        if ((int)buf[x][y] * val > 255) runtime_error(\"Char类型溢出\", {idx}, '{cmd}', '{param}');");
                        sb.AppendLine($"        buf[x][y] *= (unsigned char)val;");
                        break;
                    case '/':
                        sb.AppendLine($"        if (val == 0) runtime_error(\"0不能作为除数\", {idx}, '{cmd}', '{param}');");
                        sb.AppendLine($"        buf[x][y] /= (unsigned char)val;");
                        break;
                    case '<':
                        GenerateForwardJump(sb, idx, "val", labels);
                        sb.AppendLine($"    }}");
                        return true;
                    case '>':
                        GenerateBackwardJump(sb, idx, "val", labels);
                        sb.AppendLine($"    }}");
                        return true;
                }
                sb.AppendLine($"    }}");
                return false;
            }
            else
            {
                switch (lowerCmd)
                {
                    case 'p':
                        if (_options.Debug) sb.AppendLine($"    std::cerr << \"[Log] 参数:{param}\" << std::endl;");
                        if (_options.Debug) sb.AppendLine($"    std::cerr << \"[Warn] 结果:\" << std::endl;");
                        if (param == 'c' || param == 'C')
                            sb.AppendLine($"    std::cout.put(buf[x][y]);");
                        else if (param == 'i' || param == 'I')
                            sb.AppendLine($"    std::cout << (int)buf[x][y];");
                        else
                            sb.AppendLine($"    runtime_error(\"未知的参数\", {idx}, '{cmd}', '{param}');");
                        if (_options.Debug) sb.AppendLine($"    std::cout << std::endl;");
                        break;

                    case 'v':
                        GenerateVInstruction(sb, param, idx);
                        break;

                    case '=':
                        if (_options.Debug) sb.AppendLine($"    std::cerr << \"[Log] 参数:{param}\" << std::endl;");
                        string escaped = param switch
                        {
                            '\'' => "\\'",
                            '\\' => "\\\\",
                            _ => param.ToString()
                        };
                        sb.AppendLine($"    buf[x][y] = (unsigned char)'{escaped}';");
                        break;

                    case '+':
                    case '-':
                        GenerateAddSubInstruction(sb, cmd, param, idx);
                        break;

                    case 'i':
                        GenerateIInstruction(sb, param, idx);
                        break;

                    case '&':
                    case '|':
                    case '^':
                    case '~':
                    case ',':
                    case '.':
                        GenerateBitwiseInstruction(sb, cmd, param, idx);
                        break;

                    case 's':
                        GenerateStackInstruction(sb, param, idx);
                        break;

                    case 'f':
                        GenerateFileInstruction(sb, param, idx);
                        break;

                    default:
                        sb.AppendLine($"    runtime_error(\"未知指令\", {idx}, '{cmd}', '{param}');");
                        break;
                }
                return false;
            }
        }

        // 移动指令生成（支持 v 和 ?）
        private bool GenerateMoveInstruction(StringBuilder sb, char cmd, char param, int idx)
        {
            string coord = (char.ToLower(cmd) == 'l' || char.ToLower(cmd) == 'r') ? "x" : "y";
            string sign = (char.ToLower(cmd) == 'u' || char.ToLower(cmd) == 'l') ? "-=" : "+=";
            string boundCheck, clampValue, direction;
            if (char.ToLower(cmd) == 'u') { boundCheck = "y < 0"; clampValue = "0"; direction = "上"; }
            else if (char.ToLower(cmd) == 'd') { boundCheck = "y >= BUFSIZE"; clampValue = "BUFSIZE - 1"; direction = "下"; }
            else if (char.ToLower(cmd) == 'l') { boundCheck = "x < 0"; clampValue = "0"; direction = "左"; }
            else { boundCheck = "x >= BUFSIZE"; clampValue = "BUFSIZE - 1"; direction = "右"; }

            sb.AppendLine($"    {{ // 移动指令 {(char.ToUpper(cmd))}{param}");

            if (param == 'v')
            {
                if (_options.Debug) sb.AppendLine($"        std::cerr << \"[Log] 变量现在数值&{direction}移动距离:\" << (int)variable << std::endl;");
                sb.AppendLine($"        {coord} {sign} variable;");
                sb.AppendLine($"        if ({boundCheck}) {{");
                if (_options.Strict)
                    sb.AppendLine($"            runtime_error(\"{direction}移距离超过缓冲区边界\", {idx}, '{cmd}', '{param}');");
                else
                {
                    sb.AppendLine($"            std::cerr << \"[Warn] {direction}移距离超过缓冲区边界,自动移动到缓冲区边界\" << std::endl;");
                    sb.AppendLine($"            {coord} = {clampValue};");
                }
                sb.AppendLine($"        }}");
            }
            else if (param == '?')
            {
                string maxExpr;
                if (char.ToLower(cmd) == 'u' || char.ToLower(cmd) == 'l')
                    maxExpr = coord; // 对于 U/L，当前坐标值
                else
                    maxExpr = $"BUFSIZE - 1 - {coord}"; // 对于 D/R，剩余空间

                sb.AppendLine($"        int maxMove = {maxExpr};");
                sb.AppendLine($"        if (maxMove <= 0) {{");
                if (_options.Strict)
                    sb.AppendLine($"            runtime_error(\"{direction}移距离超过缓冲区边界\", {idx}, '{cmd}', '{param}');");
                else
                    sb.AppendLine($"            std::cerr << \"[Warn] {direction}移距离超过缓冲区边界,已取消操作\" << std::endl;");
                sb.AppendLine($"        }} else {{");
                sb.AppendLine($"            int r = rand() % maxMove + 1; // 随机 1 ~ maxMove");
                if (_options.Debug) sb.AppendLine($"            std::cerr << \"[Log] 随机到的数值&移动距离:\" << r << std::endl;");
                sb.AppendLine($"            {coord} {sign} r;");
                sb.AppendLine($"            if ({boundCheck}) {{");
                if (_options.Strict)
                    sb.AppendLine($"                runtime_error(\"{direction}移距离超过缓冲区边界\", {idx}, '{cmd}', '{param}');");
                else
                {
                    sb.AppendLine($"                std::cerr << \"[Warn] {direction}移距离超过缓冲区边界,自动移动到缓冲区边界\" << std::endl;");
                    sb.AppendLine($"                {coord} = {clampValue};");
                }
                sb.AppendLine($"            }}");
                sb.AppendLine($"        }}");
            }
            else if (char.ToLower(param) >= '0' && char.ToLower(param) <= '9' ||
                     char.ToLower(param) >= 'a' && char.ToLower(param) <= 'f' ||
                     char.ToLower(param) >= 'A' && char.ToLower(param) <= 'F')
            {
                // 十六进制立即数
                sb.AppendLine($"        int val = hex_char_to_int('{param}');");
                sb.AppendLine($"        if (val == -1) runtime_error(\"参数不是十六进制数\", {idx}, '{cmd}', '{param}');");
                if (_options.Debug) sb.AppendLine($"        std::cerr << \"[Log] 参数:\" << '{param}' << std::endl;");
                sb.AppendLine($"        {coord} {sign} val;");
                sb.AppendLine($"        if ({boundCheck}) {{");
                if (_options.Strict)
                    sb.AppendLine($"            runtime_error(\"{direction}移距离超过缓冲区边界\", {idx}, '{cmd}', '{param}');");
                else
                {
                    sb.AppendLine($"            std::cerr << \"[Warn] {direction}移距离超过缓冲区边界,自动移动到缓冲区边界\" << std::endl;");
                    sb.AppendLine($"            {coord} = {clampValue};");
                }
                sb.AppendLine($"        }}");
            }
            else
            {
                sb.AppendLine($"        runtime_error(\"参数不是一个十六进制整型或其他可能的参数\", {idx}, '{cmd}', '{param}');");
            }
            sb.AppendLine($"    }}");
            return false;
        }

        // 算术指令 + 和 - 统一处理
        private void GenerateAddSubInstruction(StringBuilder sb, char cmd, char param, int idx)
        {
            if (param == '+' && cmd == '+')
            {
                if (_options.Debug) sb.AppendLine($"    std::cerr << \"[Log] 将当前位置的值设为255\" << std::endl;");
                sb.AppendLine($"    buf[x][y] = 255;");
                return;
            }
            if (param == '-' && cmd == '-')
            {
                if (_options.Debug) sb.AppendLine($"    std::cerr << \"[Log] 将当前位置的值归零\" << std::endl;");
                sb.AppendLine($"    buf[x][y] = 0;");
                return;
            }
            if (param == '?')
            {
                if (cmd == '+')
                {
                    sb.AppendLine($"    {{");
                    sb.AppendLine($"        int maxAdd = 255 - buf[x][y];");
                    sb.AppendLine($"        if (maxAdd > 1) {{");
                    sb.AppendLine($"            int r = rand() % maxAdd + 1;");
                    if (_options.Debug) sb.AppendLine($"            std::cerr << \"[Log] 当前格的值:\" << (int)buf[x][y] << \",随机到的值:\" << r << std::endl;");
                    sb.AppendLine($"            buf[x][y] += (unsigned char)r;");
                    sb.AppendLine($"        }} else {{");
                    if (_options.Debug) sb.AppendLine($"            std::cerr << \"[Warn] 当前单元格值已满，无法随机增加\" << std::endl;");
                    sb.AppendLine($"        }}");
                    sb.AppendLine($"    }}");
                }
                else // cmd == '-'
                {
                    sb.AppendLine($"    {{");
                    sb.AppendLine($"        int maxRedu = buf[x][y];");
                    sb.AppendLine($"        if (maxRedu > 1) {{");
                    sb.AppendLine($"            int r = rand() % maxRedu + 1;");
                    if (_options.Debug) sb.AppendLine($"            std::cerr << \"[Log] 当前格的值:\" << (int)buf[x][y] << \",随机到的值:\" << r << std::endl;");
                    sb.AppendLine($"            buf[x][y] -= (unsigned char)r;");
                    sb.AppendLine($"        }} else {{");
                    if (_options.Debug) sb.AppendLine($"            std::cerr << \"[Warn] 当前单元格值已空，无法随机减少\" << std::endl;");
                    sb.AppendLine($"        }}");
                    sb.AppendLine($"    }}");
                }
                return;
            }
            // 否则当作十六进制立即数
            if ("0123456789abcdefABCDEF".Contains(param))
            {
                sb.AppendLine($"    {{");
                sb.AppendLine($"        int val = hex_char_to_int('{param}');");
                sb.AppendLine($"        if (val == -1) runtime_error(\"参数不是十六进制数\", {idx}, '{cmd}', '{param}');");
                if (_options.Debug) sb.AppendLine($"        std::cerr << \"[Log] 参数:\" << '{param}' << std::endl;");
                if (cmd == '+')
                {
                    if (_options.Strict) sb.AppendLine($"        if ((int)buf[x][y] + val > 255) runtime_error(\"Char类型溢出\", {idx}, '{cmd}', '{param}');");
                    sb.AppendLine($"        buf[x][y] += (unsigned char)val;");
                }
                else
                {
                    if (_options.Strict) sb.AppendLine($"        if ((int)buf[x][y] - val < 0) runtime_error(\"Char类型溢出\", {idx}, '{cmd}', '{param}');");
                    sb.AppendLine($"        buf[x][y] -= (unsigned char)val;");
                }
                sb.AppendLine($"    }}");
            }
            else
            {
                sb.AppendLine($"    runtime_error(\"参数不是一个十六进制整型或其他可能的参数\", {idx}, '{cmd}', '{param}');");
            }
        }

        private void GenerateForwardJump(StringBuilder sb, int idx, string valVarName, string[] labels)
        {
            sb.AppendLine($"        if ({valVarName} == 0) {{ }} // 无跳转，继续执行");
            for (int step = 1; step <= 15; step++)
            {
                int targetIdx = idx - step;
                if (targetIdx >= 0)
                {
                    sb.AppendLine($"        else if ({valVarName} == {step}) goto {labels[targetIdx]};");
                }
            }
            sb.AppendLine($"        else runtime_error(\"跳转值超出范围\", {idx}, '<', '{valVarName}');");
        }

        private void GenerateBackwardJump(StringBuilder sb, int idx, string valVarName, string[] labels)
        {
            sb.AppendLine($"        if ({valVarName} == 0) {{ }} // 无跳转，继续执行");
            for (int step = 1; step <= 15; step++)
            {
                int targetIdx = idx + step;
                if (targetIdx < labels.Length)
                {
                    sb.AppendLine($"        else if ({valVarName} == {step}) goto {labels[targetIdx]};");
                }
            }
            sb.AppendLine($"        else runtime_error(\"跳转值超出范围\", {idx}, '>', '{valVarName}');");
        }

        private void GenerateVInstruction(StringBuilder sb, char param, int idx)
        {
            if (param == '=')
            {
                if (_options.Debug) sb.AppendLine($"    std::cerr << \"[Log] 变量原数值:\" << (int)variable << std::endl;");
                sb.AppendLine($"    variable = buf[x][y];");
                if (_options.Debug) sb.AppendLine($"    std::cerr << \"[Log] 变量现数值:\" << (int)variable << std::endl;");
            }
            else if (param == 'w' || param == 'W')
            {
                sb.AppendLine($"    buf[x][y] = variable;");
                if (_options.Debug) sb.AppendLine($"    std::cerr << \"[Log] 已将变量数值写入缓冲区:\" << (int)variable << std::endl;");
            }
            else if (param == '+')
            {
                if (_options.Debug) sb.AppendLine($"    std::cerr << \"[Log] 变量原数值:\" << (int)variable << std::endl;");
                if (_options.Strict) sb.AppendLine($"    if ((int)buf[x][y] + (int)variable > 255) runtime_error(\"Char类型溢出\", {idx}, 'V', '{param}');");
                sb.AppendLine($"    variable += buf[x][y];");
                if (_options.Debug) sb.AppendLine($"    std::cerr << \"[Log] 变量现数值:\" << (int)variable << std::endl;");
            }
            else if (param == '-')
            {
                if (_options.Debug) sb.AppendLine($"    std::cerr << \"[Log] 变量原数值:\" << (int)variable << std::endl;");
                if (_options.Strict) sb.AppendLine($"    if ((int)variable - (int)buf[x][y] < 0) runtime_error(\"Char类型溢出\", {idx}, 'V', '{param}');");
                sb.AppendLine($"    variable -= buf[x][y];");
                if (_options.Debug) sb.AppendLine($"    std::cerr << \"[Log] 变量现数值:\" << (int)variable << std::endl;");
            }
            else if (param == '*')
            {
                if (_options.Debug) sb.AppendLine($"    std::cerr << \"[Log] 变量原数值:\" << (int)variable << std::endl;");
                if (_options.Strict) sb.AppendLine($"    if ((int)buf[x][y] * (int)variable > 255) runtime_error(\"Char类型溢出\", {idx}, 'V', '{param}');");
                sb.AppendLine($"    variable *= buf[x][y];");
                if (_options.Debug) sb.AppendLine($"    std::cerr << \"[Log] 变量现数值:\" << (int)variable << std::endl;");
            }
            else if (param == '/')
            {
                if (_options.Debug) sb.AppendLine($"    std::cerr << \"[Log] 变量原数值:\" << (int)variable << std::endl;");
                sb.AppendLine($"    if (buf[x][y] == 0) runtime_error(\"0不可以被用作除数\", {idx}, 'V', '{param}');");
                sb.AppendLine($"    variable /= buf[x][y];");
                if (_options.Debug) sb.AppendLine($"    std::cerr << \"[Log] 变量现数值:\" << (int)variable << std::endl;");
            }
            else if (param == '?')
            {
                if (_options.Debug) sb.AppendLine($"    std::cerr << \"[Log] 变量原数值:\" << (int)variable << std::endl;");
                sb.AppendLine($"    variable = (unsigned char)(rand() % 256);");
                if (_options.Debug) sb.AppendLine($"    std::cerr << \"[Log] 变量现数值:\" << (int)variable << std::endl;");
            }
            else
            {
                sb.AppendLine($"    runtime_error(\"未知的V参数\", {idx}, 'V', '{param}');");
            }
        }

        private void GenerateIInstruction(StringBuilder sb, char param, int idx)
        {
            if (_options.Debug) sb.AppendLine($"    std::cerr << \"[Warn] 请输入:\" << std::endl;");
            sb.AppendLine($"    ch = GETCH();");
            if (param == '+')
            {
                if (_options.Strict) sb.AppendLine($"    if ((int)buf[x][y] + ch > 255) runtime_error(\"Char类型溢出\", {idx}, 'I', '{param}');");
                sb.AppendLine($"    buf[x][y] += (unsigned char)ch;");
            }
            else if (param == '-')
            {
                if (_options.Strict) sb.AppendLine($"    if ((int)buf[x][y] - ch < 0) runtime_error(\"Char类型溢出\", {idx}, 'I', '{param}');");
                sb.AppendLine($"    buf[x][y] -= (unsigned char)ch;");
            }
            else if (param == '*')
            {
                if (_options.Strict) sb.AppendLine($"    if ((int)buf[x][y] * ch > 255) runtime_error(\"Char类型溢出\", {idx}, 'I', '{param}');");
                sb.AppendLine($"    buf[x][y] *= (unsigned char)ch;");
            }
            else if (param == '/')
            {
                sb.AppendLine($"    if (ch == 0) runtime_error(\"0不能作为除数\", {idx}, 'I', '{param}');");
                sb.AppendLine($"    buf[x][y] /= (unsigned char)ch;");
            }
            else if (param == 'w' || param == 'W' || param == '=')
            {
                sb.AppendLine($"    buf[x][y] = (unsigned char)ch;");
            }
            else
            {
                sb.AppendLine($"    runtime_error(\"未知的I参数\", {idx}, 'I', '{param}');");
            }
            if (_options.Debug) sb.AppendLine($"    std::cerr << \"[Log] 已写入[\" << x << \",\" << y << \"]\" << std::endl;");
        }

        private void GenerateBitwiseInstruction(StringBuilder sb, char cmd, char param, int idx)
        {
            char dir = char.ToLower(param);
            if (dir != 'u' && dir != 'd' && dir != 'l' && dir != 'r')
            {
                sb.AppendLine($"    runtime_error(\"方向参数必须为u/d/l/r\", {idx}, '{cmd}', '{param}');");
                return;
            }

            sb.AppendLine($"    int targetX = x, targetY = y;");
            sb.AppendLine($"    switch('{dir}') {{");
            sb.AppendLine($"        case 'u': targetY = y - 1; break;");
            sb.AppendLine($"        case 'd': targetY = y + 1; break;");
            sb.AppendLine($"        case 'l': targetX = x - 1; break;");
            sb.AppendLine($"        case 'r': targetX = x + 1; break;");
            sb.AppendLine($"    }}");
            sb.AppendLine($"    if (targetX < 0 || targetX >= BUFSIZE || targetY < 0 || targetY >= BUFSIZE)");
            sb.AppendLine($"        runtime_error(\"缓冲区溢出\", {idx}, '{cmd}', '{param}');");

            sb.AppendLine($"    unsigned char other = buf[targetX][targetY];");
            if (_options.Debug)
                sb.AppendLine($"    std::cerr << \"[Log] 相邻单元格[\" << targetX << \",\" << targetY << \"]的值:\" << (int)other << std::endl;");

            switch (cmd)
            {
                case '&':
                    sb.AppendLine($"    buf[x][y] &= other;");
                    if (_options.Debug) sb.AppendLine($"    std::cerr << \"[Log] 按位与结果:\" << (int)buf[x][y] << std::endl;");
                    break;
                case '|':
                    sb.AppendLine($"    buf[x][y] |= other;");
                    if (_options.Debug) sb.AppendLine($"    std::cerr << \"[Log] 按位或结果:\" << (int)buf[x][y] << std::endl;");
                    break;
                case '^':
                    sb.AppendLine($"    buf[x][y] ^= other;");
                    if (_options.Debug) sb.AppendLine($"    std::cerr << \"[Log] 按位异或结果:\" << (int)buf[x][y] << std::endl;");
                    break;
                case '~':
                    sb.AppendLine($"    buf[x][y] = (unsigned char)(~other);");
                    if (_options.Debug) sb.AppendLine($"    std::cerr << \"[Log] 按位取反结果:\" << (int)buf[x][y] << std::endl;");
                    break;
                case ',':
                    sb.AppendLine($"    {{");
                    sb.AppendLine($"        int result = buf[x][y] << other;");
                    if (_options.Strict)
                        sb.AppendLine($"        if (result > 255) runtime_error(\"左移结果超出255\", {idx}, '{cmd}', '{param}');");
                    sb.AppendLine($"        buf[x][y] = (unsigned char)(result & 0xFF);");
                    sb.AppendLine($"    }}");
                    if (_options.Debug) sb.AppendLine($"    std::cerr << \"[Log] 左移结果:\" << (int)buf[x][y] << std::endl;");
                    break;
                case '.':
                    sb.AppendLine($"    buf[x][y] >>= other;");
                    if (_options.Debug) sb.AppendLine($"    std::cerr << \"[Log] 右移结果:\" << (int)buf[x][y] << std::endl;");
                    break;
                default:
                    sb.AppendLine($"    runtime_error(\"未知的位运算指令\", {idx}, '{cmd}', '{param}');");
                    break;
            }
        }

        private void GenerateStackInstruction(StringBuilder sb, char param, int idx)
        {
            char sub = char.ToLower(param);
            if (_options.Debug)
            {
                sb.AppendLine($"    if (!stk.empty())");
                sb.AppendLine($"        std::cerr << \"[Log] 当前栈顶元素:\" << (int)stk.top() << std::endl;");
                sb.AppendLine($"    else");
                sb.AppendLine($"        std::cerr << \"[Log] 当前栈为空\" << std::endl;");
            }

            switch (sub)
            {
                case '+':
                    sb.AppendLine($"    stk.push(buf[x][y]);");
                    if (_options.Debug) sb.AppendLine($"    std::cerr << \"[Log] 已将\" << (int)buf[x][y] << \"压入栈顶\" << std::endl;");
                    break;
                case '-':
                    sb.AppendLine($"    if (stk.empty()) runtime_error(\"栈为空,不支持出栈\", {idx}, 'S', '{param}');");
                    sb.AppendLine($"    buf[x][y] = stk.top(); stk.pop();");
                    if (_options.Debug) sb.AppendLine($"    std::cerr << \"[Log] 已将\" << (int)buf[x][y] << \"弹出并写入缓冲区\" << std::endl;");
                    break;
                case 'c':
                    sb.AppendLine($"    while (!stk.empty()) stk.pop();");
                    if (_options.Debug) sb.AppendLine($"    std::cerr << \"[Log] 已将栈清空\" << std::endl;");
                    break;
                case '=':
                    sb.AppendLine($"    if (stk.empty()) runtime_error(\"栈为空,不支持交换\", {idx}, 'S', '{param}');");
                    sb.AppendLine($"    unsigned char tmp = stk.top(); stk.pop();");
                    sb.AppendLine($"    stk.push(buf[x][y]);");
                    sb.AppendLine($"    buf[x][y] = tmp;");
                    if (_options.Debug) sb.AppendLine($"    std::cerr << \"[Log] 已将栈顶元素与缓冲区数值交换\" << std::endl;");
                    break;
                case 's':
                    sb.AppendLine($"    buf[x][y] = (unsigned char)stk.size(); // 注意：栈大小可能超过255，只取低8位");
                    if (_options.Debug) sb.AppendLine($"    std::cerr << \"[Log] 已写入缓冲区,当前栈中项数:\" << (int)buf[x][y] << std::endl;");
                    break;
                default:
                    sb.AppendLine($"    runtime_error(\"未知的S参数\", {idx}, 'S', '{param}');");
                    break;
            }
        }

        private void GenerateFileInstruction(StringBuilder sb, char param, int idx)
        {
            if (_options.Debug)
                sb.AppendLine($"    std::cerr << \"[Log] 执行文件操作，参数:\" << '{param}' << std::endl;");

            if (param == '+' || param == '-' || param == '*' || param == '/' || param == '=')
            {
                sb.AppendLine($"    // 从输入文件读取一个字节");
                sb.AppendLine($"    if (!fin.is_open()) fin.open(input_filename, std::ios::binary);");
                sb.AppendLine($"    if (!fin) runtime_error(\"无法打开输入文件\", {idx}, 'F', '{param}');");
                sb.AppendLine($"    int b = fin.get();");
                sb.AppendLine($"    if (b == EOF) runtime_error(\"文件已读完\", {idx}, 'F', '{param}');");
                sb.AppendLine($"    unsigned char val = (unsigned char)b;");
                if (_options.Debug)
                    sb.AppendLine($"    std::cerr << \"[Log] 从文件读取的字节:\" << (int)val << std::endl;");

                switch (param)
                {
                    case '+':
                        if (_options.Strict)
                            sb.AppendLine($"    if ((int)buf[x][y] + val > 255) runtime_error(\"Char类型溢出\", {idx}, 'F', '{param}');");
                        sb.AppendLine($"    buf[x][y] += val;");
                        break;
                    case '-':
                        if (_options.Strict)
                            sb.AppendLine($"    if ((int)buf[x][y] - val < 0) runtime_error(\"Char类型溢出\", {idx}, 'F', '{param}');");
                        sb.AppendLine($"    buf[x][y] -= val;");
                        break;
                    case '*':
                        if (_options.Strict)
                            sb.AppendLine($"    if ((int)buf[x][y] * val > 255) runtime_error(\"Char类型溢出\", {idx}, 'F', '{param}');");
                        sb.AppendLine($"    buf[x][y] *= val;");
                        break;
                    case '/':
                        sb.AppendLine($"    if (val == 0) runtime_error(\"0不能作为除数\", {idx}, 'F', '{param}');");
                        sb.AppendLine($"    buf[x][y] /= val;");
                        break;
                    case '=':
                        sb.AppendLine($"    buf[x][y] = val;");
                        break;
                }
                if (_options.Debug)
                    sb.AppendLine($"    std::cerr << \"[Log] 操作后当前单元格值:\" << (int)buf[x][y] << std::endl;");
            }
            else if (param == 'c' || param == 'C' || param == 'i' || param == 'I')
            {
                bool isChar = (param == 'c' || param == 'C');
                sb.AppendLine($"    {{");
                sb.AppendLine($"        std::ofstream fout(output_filename, std::ios::app);");
                sb.AppendLine($"        if (!fout) runtime_error(\"无法打开输出文件\", {idx}, 'F', '{param}');");
                if (isChar)
                    sb.AppendLine($"        fout.put((char)buf[x][y]);");
                else
                    sb.AppendLine($"        fout << (int)buf[x][y];");
                sb.AppendLine($"        fout.close();");
                sb.AppendLine($"    }}");
                if (_options.Debug)
                    sb.AppendLine($"    std::cerr << \"[Log] 已将值写入输出文件\" << std::endl;");
            }
            else
            {
                sb.AppendLine($"    runtime_error(\"未知的F参数\", {idx}, 'F', '{param}');");
            }
        }

        private bool IsHexInstruction(char cmd)
        {
            char lower = char.ToLower(cmd);
            // 只保留 * / < >，移除了 u d l r + -
            return "*/<>".Contains(lower);
        }
    }
}